Repository MetaMorphic-Digital/complete-card-management, pull requests merged in 2024-09, with the labels that each got.

#123 Double left click now makes an image popout [#118]
  src/module/canvas/CardObject.mjs
Labels: enhancement, Canvas

#124 Scene Pile [#120]
  ccm.mjs
  lang/en.json
  src/module/canvas/CanvasCard.mjs
  src/module/canvas/CardLayer.mjs
  src/module/hooks.mjs
Labels: enhancement, Canvas

#127 [#126] Implement search filter.
  src/module/apps/CardsSheet.mjs
  templates/card/cards.hbs
Labels: Applications

#130 Bad Shuffle SVG [#129]
  assets/icons/shuffle.svg
Labels: bug, Canvas

#131 Docked Hand Sheet [#121]
  ccm.css
  lang/en.json
  module.json
  src/module/apps/CardsSheet.mjs
  src/module/hooks.mjs
  templates/card/docked.hbs
Labels: enhancement, Applications

#135 98 scrying improvements
  CHANGELOG.md
  ccm.css
  lang/en.json
  module.json
  src/module/api/scry.mjs
  templates/card/scrying-footer.hbs
  templates/card/scrying.hbs
Labels: enhancement, Applications

#138 Improved title on Card Sheet [#137]
  lang/en.json
  src/module/apps/CardSheet.mjs
Labels: Applications

#139 Region behavior improvement [#132]
  lang/en.json
  src/module/canvas/MoveCardBehavior.mjs
Labels: Canvas
